### ISSUE TITLE
Fix mini-posts avatar

### ISSUE THREAD

**Issue by htmgarcia** [topher1kenobe/wordpress-future-imperfect#5]
Before:
<img width="366" alt="before" src="https://cloud.githubusercontent.com/assets/4999794/14033977/73e73782-f1e4-11e5-9a42-0bee3667e8dc.png">

After:
<img width="377" alt="after" src="https://cloud.githubusercontent.com/assets/4999794/14033979/7a54c5f8-f1e4-11e5-9623-2bdb03a3b254.png">

I will send a new PR with changes for this one after https://github.com/topher1kenobe/wordpress-future-imperfect/pull/4

**Comment by htmgarcia** [comment]
I correct myself. These changes were already submited within that PR:
https://github.com/topher1kenobe/wordpress-future-imperfect/pull/4/commits/813c91a78a425b8ef3b3c51a125dceae5494f099

**Comment by topher1kenobe** [comment]
I merged, thanks!
